channels:
- conda-forge
dependencies:
- python =3.11
- pyiron_base =0.9.6
- versioneer =0.28
- qe=7.2
- qe-tools=2.0.0
- ase=3.23.0
- matplotlib=3.8.4
- xmlschema=3.3.1
- pygraphviz =1.13
- networkx =3.3
