channels:
- conda-forge
dependencies:
- python =3.11
- conda =23.11.0
- conda_subprocess =0.0.4
- cloudpickle =3.0.0
- gitpython =3.1.43
- h5io_browser =0.0.15
- h5py =3.11.0
- jinja2 =3.1.4
- monty =2024.5.24
- numpy =1.26.4
- pandas =2.2.2
- pint =0.24.1
- psutil =6.0.0
- pyfileindex =0.0.25
- pyiron_snippets =0.1.2
- pympipool =0.8.5
- pysqa =0.1.21
- pytables =3.9.2
- sqlalchemy =2.0.31
- tqdm =4.66.4
- traitlets =5.14.3
- versioneer =0.28
- qe=7.2
- qe-tools=2.0.0
- ase=3.23.0
- matplotlib=3.9.0
- xmlschema=3.3.1
- pygraphviz =1.13
- networkx =3.3
