name: Notebook 3.11

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.11'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 60
      run: |
        bash postBuild
        conda install -y papermill jupyter
        papermill pyiron_base_graph.ipynb pyiron_base_graph_out.ipynb -k "python3" 
      env:
        ASE_ESPRESSO_COMMAND: "pw.x -in PREFIX.pwi > PREFIX.pwo"
        ESPRESSO_PSEUDO: espresso/pseudo
