name: pyiron

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.11"
        environment-file: environment.yml
        auto-activate-base: false
    - name: Tests
      shell: bash -l {0}
      run: |
        bash postBuild
        conda install -c conda-forge jupyter papermill
        export ESPRESSO_PSEUDO=$(pwd)/espresso/pseudo
        papermill pyiron_base_graph.ipynb pyiron_base_graph_out.ipynb -k "python3"
